
version: "3.3"
services:

    frontend:
      build: ./frontend
      container_name: application
      ports:
        - "5000:5000"

    service1:
      build: ./service1
      container_name: service1
      ports:
        - "5001:5001"

    service2:    
      build: ./service2
      container_name: service2
      ports:
        - "5002:5002"

    backend:
      build: ./backend
      container_name: backend
      ports:
        - "5003:5003"

    nginx:
      image: nginx:latest
      container_name: DnDnginx
      ports:
      - "80:80"
      
      volumes:
        - type: bind
      source: ./nginx/nginx.conf

        

    mysql:
      image: mysql:5.7
      build: ./frontend/db
      container_name: mysql


